### ISSUE TITLE
enable PDF format of the book.

### ISSUE THREAD

**Issue by ryanrhymes** [owlbarn/book#28]
This will take some efforts. I was close last time, but got some issues in embedding the images.

also require latex will bloat the docker image a lot.

**Comment by jzstark** [comment]
Just list the possible causes we have found  to the disappearance of TOC in pdf:
- non-ASCII characters 
- unclosed/unmatched "$" in using LaTeX math
- ...

**Comment by ryanrhymes** [comment]
O I forgot to close this ...
