### ISSUE TITLE
Fix the LaTeX render problem in markdown

### ISSUE THREAD

**Issue by jzstark** [owlbarn/book#31]
In the markdown file, LaTeX expression such as `$\sqrt{2}$` will fail with message `[WARNING] Could not convert TeX math '\sqrt{2}', rendering as TeX`.  Using `$\sqrt\{2\}$` does not fix the problem. 

This issue might be caused by `pandoc`.

**Comment by ryanrhymes** [comment]
solved in https://github.com/owlbarn/book/commit/0ab79ab7d79b150f8e23928e1cd2306722b6973f
